import * as core from '@actions/core';
import * as github from '@actions/github';
import { RepoReport } from './analyzer';

export async function createIssue(
  token: string,
  reports: RepoReport[]
): Promise<string> {
  const octokit = github.getOctokit(token);
  const { owner, repo } = github.context.repo;

  const now = new Date();
  const title = `[repo-intel] Competitive Intelligence Report — ${now.toISOString().split('T')[0]}`;

  let body = `# Competitive Intelligence Report\n`;
  body += `*Generated by [repo-intel](https://github.com/marketplace/actions/repo-intel) on ${now.toISOString().split('T')[0]}*\n\n`;
  body += `---\n\n`;

  for (const report of reports) {
    body += report.markdown;
    body += `\n---\n\n`;
  }

  // Summary section
  const highSignals = reports.flatMap(r => r.signals.filter(s => s.level === 'HIGH'));
  if (highSignals.length > 0) {
    body += `## ⚠️ High Priority Signals\n\n`;
    for (const signal of highSignals) {
      body += `- ${signal.message}\n`;
    }
    body += `\n`;
  }

  const { data: issue } = await octokit.rest.issues.create({
    owner,
    repo,
    title,
    body,
    labels: ['repo-intel'],
  });

  core.info(`Created issue: ${issue.html_url}`);
  return issue.html_url;
}

export async function createPRComment(
  token: string,
  reports: RepoReport[]
): Promise<void> {
  const octokit = github.getOctokit(token);
  const { owner, repo } = github.context.repo;
  const prNumber = github.context.payload.pull_request?.number;

  if (!prNumber) {
    core.warning('No pull request context found, falling back to JSON output');
    outputJson(reports);
    return;
  }

  let body = `## repo-intel Report\n\n`;
  for (const report of reports) {
    body += report.markdown + `\n`;
  }

  await octokit.rest.issues.createComment({
    owner,
    repo,
    issue_number: prNumber,
    body,
  });

  core.info(`Posted comment on PR #${prNumber}`);
}

export function outputJson(reports: RepoReport[]): string {
  const json = JSON.stringify(
    reports.map(r => ({
      owner: r.owner,
      repo: r.repo,
      period: { start: r.periodStart, end: r.periodEnd, days: r.periodDays },
      activity: r.activity,
      signals: r.signals,
      recommendation: r.recommendation,
    })),
    null,
    2
  );

  core.info('Report JSON:');
  core.info(json);
  return json;
}
