import * as https from 'https';
import * as core from '@actions/core';
import { RepoReport } from './analyzer';

interface SlackBlock {
  type: string;
  [key: string]: unknown;
}

function buildSlackBlocks(reports: RepoReport[]): SlackBlock[] {
  const blocks: SlackBlock[] = [
    {
      type: 'header',
      text: { type: 'plain_text', text: '🔍 Repo Intel Report', emoji: true },
    },
    { type: 'divider' },
  ];

  for (const r of reports) {
    blocks.push({
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*<https://github.com/${r.owner}/${r.repo}|${r.owner}/${r.repo}>*`,
      },
    });

    const fields: Array<{ type: string; text: string }> = [
      { type: 'mrkdwn', text: `*Stars:* ${r.stars}` },
      { type: 'mrkdwn', text: `*Forks:* ${r.forks}` },
      { type: 'mrkdwn', text: `*Commits (period):* ${r.commits.current}` },
      { type: 'mrkdwn', text: `*PRs merged:* ${r.pullRequests.mergedInPeriod}` },
      { type: 'mrkdwn', text: `*Issues opened:* ${r.issues.openedInPeriod}` },
      { type: 'mrkdwn', text: `*New contributors:* ${r.contributors.newInPeriod}` },
    ];

    blocks.push({ type: 'section', fields });

    if (r.releases.recent.length > 0) {
      const releaseList = r.releases.recent
        .slice(0, 3)
        .map(rel => `• \`${rel.tag}\` — ${rel.name}`)
        .join('\n');
      blocks.push({
        type: 'section',
        text: { type: 'mrkdwn', text: `*Recent releases:*\n${releaseList}` },
      });
    }

    blocks.push({ type: 'divider' });
  }

  blocks.push({
    type: 'context',
    elements: [
      {
        type: 'mrkdwn',
        text: `Generated by <https://github.com/oxnr/repo-intel|repo-intel> · ${new Date().toUTCString()}`,
      },
    ],
  });

  return blocks;
}

function postToSlack(webhookUrl: string, payload: object): Promise<void> {
  return new Promise((resolve, reject) => {
    const body = JSON.stringify(payload);
    const url = new URL(webhookUrl);
    const options = {
      hostname: url.hostname,
      path: url.pathname + url.search,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body) },
    };

    const req = https.request(options, res => {
      let data = '';
      res.on('data', chunk => (data += chunk));
      res.on('end', () => {
        if (res.statusCode && res.statusCode >= 200 && res.statusCode < 300) {
          resolve();
        } else {
          reject(new Error(`Slack webhook returned status ${res.statusCode}: ${data}`));
        }
      });
    });

    req.on('error', reject);
    req.write(body);
    req.end();
  });
}

export async function sendSlackNotification(
  webhookUrl: string,
  reports: RepoReport[]
): Promise<void> {
  const blocks = buildSlackBlocks(reports);
  const payload = { blocks };

  try {
    await postToSlack(webhookUrl, payload);
    core.info('Slack notification sent successfully.');
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    core.warning(`Failed to send Slack notification: ${msg}`);
  }
}
